<?php

namespace OC\Billingbundle\Repository

/**
 * TicketRepository
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepostory extends \Doctrine\ORM\EntityRepository
{
}
